FROM python:3.11-slim

WORKDIR /app

RUN pip install --no-cache-dir \
    streamlit \
    plotly \
    pandas \
    pyhive \
    thrift \
    thrift-sasl \
    pure-sasl \
    python-dotenv \
    openai \
    "streamlit-cookies-manager==0.2.0" \
    openpyxl 

EXPOSE 8501

CMD ["streamlit", "run", "app.py", "--server.address", "0.0.0.0", "--server.port", "8501"]